import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
const root = fileURLToPath(new URL('../', import.meta.url));
const read = name => readFileSync(path.join(root, name), 'utf8');
let page = read('src/pages/home.html');
for (const name of ['lead-offer', 'site-header', 'site-footer', 'float-actions']) page = page.replace(`{{${name}}}`, () => read(`src/components/${name}.html`).trim());
assert.equal(read('index.html'), read('src/document.html').replace('{{page}}', () => page.trim()), 'Run npm run build: HTML is stale');
for (const [built, source] of [['styles/site-v7.css', 'src/styles/site.css'], ['scripts/site-v5.js', 'src/scripts/site.js']]) assert.equal(read(built), read(source), `${built} is stale`);
const html = read('index.html');
assert.match(html, /name="robots" content="noindex, nofollow"/);
assert(!/cs-nav-asset-icon/.test(html), 'Navigation icons returned');
assert.match(html, /src="assets\/brand\/logo1.webp"/);
assert.match(html, /data-cs-lead-modal/);
assert.match(html, /data-cs-lead-sticky/);
assert.match(html, /Preview form only\. No lead will be submitted\./);
assert(!/cs-utility/.test(html), 'Removed utility bar returned');
assert(!/\/Users\/|127\.0\.0\.1|localhost/.test(html), 'Local-only URL in page');
new vm.Script(read('scripts/site-v5.js'));
const check = (ref, base) => {
  if (/^(?:[a-z]+:|\/\/|#)/i.test(ref)) return;
  const clean = decodeURIComponent(ref.split(/[?#]/)[0]);
  if (!clean || clean === './') return;
  assert(!clean.startsWith('/'), `Root-relative reference breaks repository hosting: ${ref}`);
  assert(existsSync(path.resolve(root, base, clean)), `Missing local file: ${ref}`);
};
for (const match of html.matchAll(/(?:src|data-src|href)="([^"]+)"/g)) check(match[1], '.');
for (const match of read('styles/site-v7.css').matchAll(/url\(\s*['"]?([^'"\s)]+)['"]?\s*\)/g)) check(match[1], 'styles');
const manifest = JSON.parse(read('docs/asset-manifest.json'));
for (const asset of manifest.images) assert(existsSync(path.join(root, asset.packaged)), asset.packaged);
console.log(`PASS: reproducible build, JavaScript syntax, staging noindex, navigation, official star and ${manifest.images.length} assets. External services and WordPress remain separate checks.`);
